import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const inter = Poppins({
  subsets: ["latin"], style: ["normal"],
  weight: "400"
});;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className="dark">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  );
}
